version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    network_mode: "host"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    network_mode: "host"

#  app:
#    image: inno-taxi:latest
#    container_name: your_app
#    restart: always
#    network_mode: "host"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - redis
#    env_file:
#      - ./config/.env

networks:
  my_network:
